### PR TITLE
Return ExtendedErrorInfo in addition to ErrDesc for Response->getError()

### LINKED ISSUE #10: getError() returns ErrDesc instead of ExtendedErrorInfo even when ExtendedErrorInfo is available
In `Response->getError()`, it only returns the ErrDesc. For some errors, `ExtendedErrorInfo` is set in the XML response. getError() should be returning that instead of ErrDesc when available, or it should combine the two.

Example - below, ExtendedErrorInfo gives a much better explanation of what happened than ErrDesc. Currently, we only return ErrDesc, which leaves the calling code wondering what happened.
```
<YourMembership_Response>
  <ErrCode>404</ErrCode>
  <ExtendedErrorInfo>[GroupCode] is invalid; it must be unique</ExtendedErrorInfo>
  <ErrDesc>Method call failed. One or more arguments is missing or invalid.</ErrDesc>
  <XmlRequest>
  </XmlRequest>
</YourMembership_Response>
```

### PR DESCRIPTION
**Pull request by tlshaheen**
If ExtendedErrorInfo is set, return that in the same string as ErrDesc inside `Response->getError()`

Resolves #10

### CODE REVIEW

File: src/Core/Response.php [hunk 1]
```diff
@@ -45,21 +45,27 @@ public function getErrorCode() : int
...
+	 * Fetches the Error Message (including Extended Error Info) From Response
 	 * @method getError
 	 * @author PA
 	 * @date   2017-01-10
 	 * @return string     Error Message
 	 */
 	public function getError() : string
 	{
-		return (string) $this->response->ErrDesc;
+	    $extendedErrorInfo = isset($this->response->ExtendedErrorInfo) ? (string) $this->response->ExtendedErrorInfo : '';
```
Comment (Ikstar) [inline src/Core/Response.php]: To keep the functions small and simple, getExtendedError can be its own function.

File: src/Core/Response.php [hunk 2]
```diff
@@ -45,21 +45,27 @@ public function getErrorCode() : int
...
+	    $error = isset($this->response->ErrDesc) ? (string) $this->response->ErrDesc : '';
```
Comment (Ikstar) [inline src/Core/Response.php]: 1. $this->response->ErrDesc always exists when the function is called. so it does not need to check for isset.

If it doesn't exist we should be throwing an exception here, because the ErrDesc is not present when it should be.

File: src/Core/Response.php [hunk 3]
```diff
@@ -45,21 +45,27 @@ public function getErrorCode() : int
...
+	    if ($extendedErrorInfo) {
+	        $error .= " ($extendedErrorInfo)";
```
Comment (Ikstar) [inline src/Core/Response.php]: Updated the function, but did not update the test...

**Review by Ikstar — CHANGES_REQUESTED** [review]

**Review by Ikstar — APPROVED** [review]
